PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX schema: <https://schema.org/>
PREFIX wd: <http://www.wikidata.org/entity/>
SELECT DISTINCT * WHERE {
  VALUES ?wd {wd:Q411181}
  ?wd schema:sameAs ?uniprot  .
  ?disprot schema:sameAs ?uniprot ;
           schema:hasRepresentation ?sequence ;
           rdf:type ?type .
}